import type { Metadata } from 'next';
import './globals.css';
import type React from 'react';
import SiteFooter from '@/components/footer';
import { MainNav } from '@/components/navbar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={'antialiased'}>
                <div className='flex min-h-screen flex-col'>
                    <header className='z-40 mx-auto bg-background'>
                        <div className='flex h-10 items-center justify-between py-6 '>
                            {/* <span className='text-sm lg:text-xl xl:text-2xl'>Alex Westerman</span> */}

                            <MainNav />
                        </div>
                    </header>

                    <main className='flex flex-1 flex-grow flex-col'>
                        {children}
                        <div className='flex items-center'>
                            <SiteFooter />
                        </div>
                    </main>
                </div>
            </body>
        </html>
    );
}
